<a href="https://colab.research.google.com/github/milindkhare/milindkhare/blob/Pypractice/ML_scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data extraction
---



In [2]:
import pandas as pd

# Breast cancer data
cancer_set = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', 
                        header = None)
print(cancer_set.shape)
cancer_set.head()

(569, 32)


0  1      2      3       4   ...      27      28      29      30       31
0    842302  M  17.99  10.38  122.80  ...  0.6656  0.7119  0.2654  0.4601  0.11890
1    842517  M  20.57  17.77  132.90  ...  0.1866  0.2416  0.1860  0.2750  0.08902
2  84300903  M  19.69  21.25  130.00  ...  0.4245  0.4504  0.2430  0.3613  0.08758
3  84348301  M  11.42  20.38   77.58  ...  0.8663  0.6869  0.2575  0.6638  0.17300
4  84358402  M  20.29  14.34  135.10  ...  0.2050  0.4000  0.1625  0.2364  0.07678

[5 rows x 32 columns]

In [8]:
# Feature extraction
# First is id and second is tumor type, rest are features
cancer_features = cancer_set.iloc[:,2:] # all rows, all cols after 2

print(cancer_features.shape)
print(type(cancer_features))

#cancer_features is a dataframe. It is converted to a numpy array with below code
cancer_features = cancer_features.values
print(type(cancer_features))
print(cancer_features.shape)

(569, 30)
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
(569, 30)


In [9]:
#cancer_features[1]
# put up the column headers
cancer_features_names = ['mean radius', 
'mean texture', 'mean perimeter', 
'mean area', 'mean smoothness', 
'mean compactness', 'mean concavity',
'mean concave points', 'mean symmetry',
'mean fractal dimension','radius error',
'texture error','perimeter error',
'area error', 'smoothness error',
'compactness error','concavity error',
'concave points error','symmetry error',
'fractal dimension error','worst radius',
'worst texture', 'worst perimeter', 
'worst area','worst smoothness', 
'worst compactness', 'worst concavity',
'worst concave points','worst symmetry',
'worst fractal dimension']

In [10]:
# Set target variable
cancer_target = cancer_set.iloc[:,1]

#Replacing factor with binary 0,1
cancer_target = cancer_target.replace(['M', 'B'], [0,1])
cancer_target = cancer_target.values

print(cancer_target.shape)

(569,)


Fetching same with inbuilt dataset of Scikit learn

import sklearn.datasets as datasets
cancer = datasets.load_breast_cancer()
print(cancer.data.shape)
print(cancer.target.shape)

In [3]:
import sklearn.datasets as datasets
#cancer = datasets.load_breast_cancer()
iris = datasets.load_iris()
print(type(iris))
#iris.data

<class 'sklearn.utils.Bunch'>


# Preprocessing

Standardization

In [4]:
import sklearn.preprocessing as preprocessing

#standardizer = preprocessing.StandardScaler()
#standardizer = standardizer.fit(breast_cancer.data)
#breast_cancer_standardized = standardizer.transform(breast_cancer.data)

# print('Mean of each feature after Standardization :\n\n')
# print(breast_cancer_standardized.mean(axis=0))
# print('\nStd. of each feature after Standardization :\n\n')
# print(breast_cancer_standardized.std(axis=0))

In [13]:
standardizer = preprocessing.StandardScaler()
#print(cancer_features)
cancer_features_std = standardizer.fit_transform(cancer_features)

print(cancer_features_std.shape)
print(cancer_features_std.mean(axis=0))
print(cancer_features_std.std(axis=0))

(569, 30)
[-1.37363271e-16  6.86816353e-17 -1.24875700e-16 -2.18532476e-16
  1.74825981e-16  1.99801121e-16  3.74627101e-17 -3.74627101e-17
  1.87313551e-16  4.52674414e-16  2.49751401e-16 -1.03022453e-16
 -3.49651961e-16 -1.31119486e-16  4.40186844e-16  1.81069766e-16
  1.62338411e-16  1.24875700e-17  8.11692053e-17  6.24378502e-18
 -8.24179623e-16  1.24875700e-17 -3.74627101e-16  0.00000000e+00
 -2.37263831e-16 -3.37164391e-16  7.49254203e-17  2.24776261e-16
  2.74726541e-16  2.12288691e-16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [15]:
# Scaling transforms existing data values to lie between a minimum and maximum value.
# MinMaxScaler transforms data to range 0 and 1.
# MaxAbsScaler transforms data to range -1 and 1.

#breast_cancer_minmaxscaled = preprocessing.MinMaxScaler().fit_transform(cancer_features) # deafult is btw 0 n 1
# min max with particular range
breast_cancer_minmaxscaled = preprocessing.MinMaxScaler(feature_range=(0, 10)).fit_transform(cancer_features)

breast_cancer_minmaxscaled.mean(axis=0)


array([3.38221957, 3.23965117, 3.32935066, 2.16920086, 3.94784519,
       2.60600528, 2.08058378, 2.43136908, 3.79605368, 2.70379314,
       1.06345123, 1.89324042, 0.99376112, 0.62635794, 1.81119044,
       1.74438511, 0.80539688, 2.23454008, 1.78143451, 1.00192912,
       2.96662747, 3.63998486, 2.83137669, 1.70906196, 4.04137846,
       2.20212323, 2.17402942, 3.93835819, 2.63306862, 1.89596073])

Normalization

  'l1' norm makes the sum of absolute values of each row as 1, and 'l2' norm makes the sum of squares of each row as 1.
  'l1' norm is insensitive to outliers and by default l2 norm is considered. Hence, removing outliers is recommended before applying l2 norm.

In [20]:
cancer_normalizer = preprocessing.Normalizer(norm='l1').fit_transform(cancer_features)
cancer_normalizer1 = preprocessing.Normalizer(norm='l2').fit_transform(cancer_features)
print(cancer_features.mean(axis=0))
print(cancer_normalizer.mean(axis=0))
print(cancer_normalizer1.mean(axis=0))
#breast_cancer_normalized = normalizer.transform(breast_cancer.data)

[1.41272917e+01 1.92896485e+01 9.19690334e+01 6.54889104e+02
 9.63602812e-02 1.04340984e-01 8.87993158e-02 4.89191459e-02
 1.81161863e-01 6.27976098e-02 4.05172056e-01 1.21685343e+00
 2.86605923e+00 4.03370791e+01 7.04097891e-03 2.54781388e-02
 3.18937163e-02 1.17961371e-02 2.05422988e-02 3.79490387e-03
 1.62691898e+01 2.56772232e+01 1.07261213e+02 8.80583128e+02
 1.32368594e-01 2.54265044e-01 2.72188483e-01 1.14606223e-01
 2.90075571e-01 8.39458172e-02]
[1.48431741e-02 2.20102116e-02 9.60057252e-02 6.05084121e-01
 1.12637599e-04 1.09920831e-04 7.93195454e-05 4.21104980e-05
 2.12177723e-04 7.55815095e-05 3.96889256e-04 1.49250031e-03
 2.79802882e-03 3.33160008e-02 8.95511912e-06 2.86915349e-05
 3.55450350e-05 1.27935813e-05 2.52658404e-05 4.66426598e-06
 1.67445961e-02 2.91619161e-02 1.09652103e-01 7.77287215e-01
 1.54636457e-04 2.61800359e-04 2.60829513e-04 1.08304876e-04
 3.35088957e-04 9.88076119e-05]


Binarization

based on threshold

In [21]:
binarizer = preprocessing.Binarizer(threshold=3.0).fit(cancer_features)
breast_cancer_binarized = binarizer.transform(cancer_features) # above 3 as 1 else 0
print(breast_cancer_binarized[:5,:5])

[[1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]]


One hot encoder
numerical values to binary

In [27]:
onehotencoder = preprocessing.OneHotEncoder()
onehotencoder = onehotencoder.fit_transform([[1], [1], [1], [2], [2], [1]])

# Transforming category values 1 and 2 to one-hot vectors
print(onehotencoder)
print(onehotencoder[[4]].toarray())

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
[[0. 1.]]


In [52]:
iris_1 = iris.target.reshape(-1,1)
print(iris.target[[0,50,100]])
print(iris_1[50], iris_1[100])

iris_target_onehot = preprocessing.OneHotEncoder().fit_transform(iris_1)
print(iris_target_onehot.toarray()[[0,50,100]])


[0 1 2]
[1] [2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Label encoding

In [32]:
labels = ['malignant', 'benign', 'malignant', 'benign']

labelencoder = preprocessing.LabelEncoder()

labelencoder = labelencoder.fit_transform(labels)
print(labelencoder)

#bc_labelencoded = labelencoder.transform(cancer_set.iloc[:,1])

[1 0 1 0]


Imputer

In [ ]:
imputer = preprocessing.Imputer(missing_values='NaN', strategy='mean', axis = 0)

imputer = imputer.fit_transform(cancer_features)

In [ ]:
##Practice
import sklearn.preprocessing as preprocessing

# regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
# print(preprocessing.LabelEncoder().fit(regions).transform(regions))

# import sklearn.preprocessing as preprocessing

# x = [[7.8], [1.3], [4.5], [0.9]]
# print(preprocessing.Binarizer().fit(x).transform(x))

# x = [[0, 0], [0, 1], [2,0]]
# enc = preprocessing.OneHotEncoder()
# print(enc.fit(x).transform([[1, 1]]).toarray())

# imputation
iris.data[:50] = numpy.nan

print(iris.data[48:55,])
#imputer = preprocessing.Imputation(missing_values= numpy.NaN, strategy='mean', axis = 0)
iris_imputed = preprocessing.Imputer(missing_values='NaN', strategy='mean').fit_transform(iris.data)
iris_imputed = imputer.fit_transform(iris.data)

print(iris_imputed.mean(axis=0))

In [38]:
iris = datasets.load_iris()

norm = preprocessing.Normalizer(norm='l2')

iris_normalized = norm.fit_transform(iris.data)
print(iris_normalized.mean(axis=0))

[0.75140029 0.40517418 0.45478362 0.14107142]


# Nearest Neighbours

There are nearest neighbour classifier and regressors in scikit learn
which uses 2 algos - 

KNeighbors predicts based on the k nearest neighbors of each query point.

RadiusNeighbors predicts based on the neighbors present in a fixed radius r of the query point.

In [10]:
import sklearn.datasets as datasets

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

cancer = datasets.load_breast_cancer()  # Loading the data set

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(cancer.data, cancer.target,
           stratify=cancer.target, random_state=42)

knn_classifier = KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, Y_train)

sklearn.neighbors.

In [13]:
print('Accuracy of Train Data :', knn_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', knn_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9460093896713615
Accuracy of Test Data : 0.9300699300699301


# Decision Tree

Decision trees sometimes become complex, which do not generalize well and leads to overfitting. 

Overfitting can be addressed by placing the least number of samples needed at a leaf node or placing the highest depth of the tree.

A small variation in data can result in a completely different tree. This problem can be addressed by using decision trees within an ensemble.

In [17]:
from sklearn.tree import DecisionTreeClassifier
# taking cancer train and test data only
dt_classifier = DecisionTreeClassifier()
dt_classifier = dt_classifier.fit(X_train, Y_train)

print('Accuracy of Train Data :', dt_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', dt_classifier.score(X_test,Y_test))


Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.9370629370629371


In [18]:
# tuning model to avoid overfitting
dt_classifier = DecisionTreeClassifier(max_depth=2)   

dt_classifier = dt_classifier.fit(X_train, Y_train) 

print('Accuracy of Train Data :', dt_classifier.score(X_train,Y_train))

print('Accuracy of Test Data :', dt_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9460093896713615
Accuracy of Test Data : 0.9230769230769231


# Ensemble Trees

Ensemble Methods

Ensemble methods combine predictions of other learning algorithms, to improve the generalization.

Ensemble methods are two types:

Averaging Methods: They build several base estimators independently and finally average their predictions.
  E.g.: Bagging Methods, Forests of randomised trees

Boosting Methods: They build base estimators sequentially and try to reduce the bias of the combined estimator.
  E.g.: Adaboost, Gradient Tree Boosting

##Bagging Methods

Bagging Methods draw random subsets of the original dataset, build an estimator and aggregate individual results to form a final one.

BaggingClassifier and BaggingRegressor are the utilities from sklearn.ensemble to deal with Bagging.

sklearn.ensemble offers two types of algorithms based on randomized trees: Random Forest and Extra randomness algorithms.

Random Forests

RandomForestClassifier and RandomForestRegressor classes are used to deal with random forests. In random forests, each estimator is built from a sample drawn with replacement from the training set.

Randomized Trees

ExtraTreesClassifier and ExtraTreesRegressor classes are used to deal with extremely randomized forests. In extremely randomized forests, more randomness is introduced, which further reduces the variance of the model.

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier()

rf_classifier = rf_classifier.fit(X_train, Y_train) 

print('Accuracy of Train Data :', rf_classifier.score(X_train,Y_train))

print('Accuracy of Test Data :', rf_classifier.score(X_test,Y_test))

Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.958041958041958


##Boosting Methods

Boosting Methods combine several weak models to create a improvised ensemble.

sklearn.ensemble also provides the following boosting algorithms:

AdaBoostClassifier & 
GradientBoostingClassifier

# Support Vector Machines

Support Vector Machines (SVMs) separates data points based on decision planes, which separates objects belonging to different classes in a higher dimensional space.

SVM algorithm uses the best suitable kernel, which is capable of separating data points into two or more classes.

Commonly used kernels are:

linear

polynomial

rbf

sigmoid

scikit-learn provides the following three utilities for performing Support Vector Classification.

SVC,
NuSVC: Same as SVC but uses a parameter to control the number of support vectors.
LinearSVC: Similar to SVC with parameter kernel taking linear value.

Advantages of SVMs

SVM can distinguish the classes in a higher dimensional space.

SVM algorithms are memory efficient.

SVMs are versatile, and a different kernel can be used by a decision function.

Disadvantages of SVMs

SVMs do not perform well on high dimensional data with many samples.

SVMs work better only with Preprocessed data.

They are harder to visualize.

In [20]:
from sklearn.svm import SVC

svm_classifier = SVC()

svm_classifier = svm_classifier.fit(X_train, Y_train) 

print('Accuracy of Train Data :', svm_classifier.score(X_train,Y_train))

print('Accuracy of Test Data :', svm_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9178403755868545
Accuracy of Test Data : 0.9230769230769231


In [22]:
import sklearn.preprocessing as preprocessing

standardizer = preprocessing.StandardScaler()
standardizer = standardizer.fit(cancer.data)
cancer_standardized = standardizer.transform(cancer.data)

X_train, X_test, Y_train, Y_test = train_test_split(cancer_standardized, cancer.target,
           stratify=cancer.target, random_state=42)
svm_classifier = SVC()

svm_classifier = svm_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', svm_classifier.score(X_train,Y_train))

print('Accuracy of Test Data :', svm_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9788732394366197
Accuracy of Test Data : 0.9790209790209791


In [23]:
from sklearn import metrics

Y_pred = svm_classifier.predict(X_test)

print('Classification report : \n',metrics.classification_report(Y_test, Y_pred))

Classification report : 
               precision    recall  f1-score   support

           0       0.96      0.98      0.97        53
           1       0.99      0.98      0.98        90

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143

